export default [
  {
    name: "Incentive1_1",
    title: {
      text: "Add a Test T-shirt to your order",
      fontFamily: "Roboto",
      lineHeight: "20px",
      fontSize: "24px",
      color: "#ffffff",
      paddingTop: "16px",
      paddingLeft: "",
      paddingRight: "",
      paddingBottom: "18px",
      marginTop: "",
      marginBottom: "",
      marginLeft: "",
      marginRight: "",
      visibility: true,
    },
    subTitle: {
      text: "Exclusive offer expires in:",
      fontFamily: "Roboto",
      lineHeight: "20px",
      fontSize: "18px",
      color: "#ffffff",
      paddingTop: "",
      paddingLeft: "",
      paddingRight: "",
      paddingBottom: "14px",
      marginTop: "",
      marginBottom: "",
      marginLeft: "",
      marginRight: "",
      visibility: true,
    },
    countdown: {
      duration: "5",
      visibility: true,
    },
    background: { backgroundColor: "rgb(0, 128, 96)" },
    layout: {
      paddingTop: "22px",
      paddingRight: "10px",
      paddingBottom: "2px",
      paddingLeft: "10px",
      marginTop: "",
      marginBottom: "",
      marginLeft: "",
      marginRight: "",
    },
  },
  // product:{
  //   layout:'right',
  //   productDescription:{
  //     style:{
  //       fontFamily:'Roboto'

  //     }
  //   }
  // },
  {
    name: "Content1_1",
    imagePosition: "left",
    images: [
      {
        url: "/image/guy_1.jpg",
      },
    ],
    title: {
      text: "Test T-shirt",
      fontFamily: "Roboto",
      lineHeight: "20px",
      fontSize: "24px",
      fontWeight: 600,
      fontColor: "black",
      margin: "0 0 21px 0",
      visibility: true,
    },
    subTitle: {
      text: "Include a short, benefit-driven description of what your product does and how it can improve your customer's life.",
      price: 20,
      fontFamily: "Roboto",
      lineHeight: "20px",
      fontWeight: 400,
      fontSize: "16px",
      fontColor: "black",
      padding: 0,
      margin: 0,
      visibility: true,
    },
  },
  {
    name: "Content1_2",
    imagePosition: "right",
    title: {
      text: "Headline Content 1",
      fontFamily: "Roboto",
      lineHeight: "20px",
      fontSize: "24px",
      fontWeight: 600,
      fontColor: "black",
      margin: "0 0 21px 0",
      visibility: true,
    },
    subTitle: {
      text: "You could highlight specific ingredients, materials, or functionality that make your product unique, and explain how it will improve the customer's life.",
      fontFamily: "Roboto",
      lineHeight: "20px",
      fontWeight: 400,
      fontSize: "16px",
      fontColor: "black",
      padding: 0,
      margin: 0,
      visibility: true,
    },
  },
];
